#!/usr/bin/env node
// Downloads every theme's fonts from Google Fonts into a local directory so
// decks render with the right typefaces on hosts without internet access, and
// so PDFs don't depend on a third-party CDN at export time. Run at image build
// (see Dockerfile) or locally with `pnpm fonts` after `pnpm build`.
//
// Output: <out>/<theme>.css (@font-face with relative URLs), <out>/*.woff2,
// <out>/manifest.json. All fonts used by the themes are SIL OFL 1.1, which
// permits bundling and redistribution.
import { mkdir, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { THEMES } from '../dist/themes.js';

const out = path.resolve(process.argv[2] ?? 'fonts');
// A current desktop Chrome UA makes Google serve woff2 split by unicode range.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';
// Decks are Russian/English; Greek and Vietnamese subsets only add weight.
const KEEP = new Set(['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext']);

async function get(url, as) {
  for (let attempt = 1; ; attempt++) {
    try {
      const res = await fetch(url, { headers: { 'user-agent': UA } });
      if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
      return as === 'text' ? await res.text() : Buffer.from(await res.arrayBuffer());
    } catch (err) {
      if (attempt >= 4) throw err;
      await new Promise(r => setTimeout(r, 2 ** attempt * 1000));
    }
  }
}

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

const files = new Map(); // remote url -> local file name
let bytes = 0;
for (const theme of Object.values(THEMES)) {
  const css = await get(`https://fonts.googleapis.com/css2?${theme.googleFonts.map(f => `family=${f}`).join('&')}&display=block`, 'text');
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*{[^}]*})/g)];
  if (!blocks.length) throw new Error(`no @font-face blocks for theme ${theme.id}`);
  const kept = [];
  for (const [, subset, block] of blocks) {
    if (!KEEP.has(subset)) continue;
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) throw new Error(`no woff2 url in ${theme.id}/${subset}`);
    if (!files.has(url)) {
      const data = await get(url, 'buffer');
      const family = block.match(/font-family:\s*'([^']+)'/)[1].toLowerCase().replace(/\s+/g, '-');
      const name = `${family}-${subset}-${createHash('sha1').update(url).digest('hex').slice(0, 8)}.woff2`;
      await writeFile(path.join(out, name), data);
      files.set(url, name);
      bytes += data.length;
    }
    kept.push(`/* ${subset} */\n${block.replace(url, `./${files.get(url)}`)}`);
  }
  await writeFile(path.join(out, `${theme.id}.css`), kept.join('\n') + '\n');
}

await writeFile(path.join(out, 'manifest.json'), JSON.stringify({
  generated: new Date().toISOString(),
  themes: Object.keys(THEMES),
  files: files.size,
  bytes,
}, null, 2));
const families = [...new Set(Object.values(THEMES).flatMap(t => Object.values(t.fonts)))].sort();
await writeFile(path.join(out, 'README.md'), `# Bundled fonts

Generated by \`scripts/fetch-fonts.mjs\` from Google Fonts — do not edit by
hand; rerun the script after changing a theme's fonts.

All families are licensed under the SIL Open Font License 1.1
(https://openfontlicense.org), which allows bundling and redistribution:

${families.map(f => `- ${f} — https://fonts.google.com/specimen/${f.replace(/ /g, '+')}`).join('\n')}
`);
console.log(`fonts: ${files.size} files, ${(bytes / 1024 / 1024).toFixed(1)} MB → ${out}`);
